// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wykysgikszfhpblaygpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5a3lzZ2lrc3pmaHBibGF5Z3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTYyNzYsImV4cCI6MjA1OTk3MjI3Nn0._Y3acDjLwdCqj64ij0AJCdBbU6Exv8rctPIVmYQKclc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);